SELECT A.FLAVOR
FROM (
    SELECT F.FLAVOR, (
            SUM(DISTINCT F.TOTAL_ORDER) + 
            SUM(DISTINCT J.TOTAL_ORDER)) AS TOTAL
    FROM JULY J LEFT JOIN FIRST_HALF F 
                ON F.FLAVOR = J.FLAVOR 
    GROUP BY F.FLAVOR
    ORDER BY TOTAL DESC 
    LIMIT 3
    ) A