# SELECT FLAVOR
# FROM FIRST_HALF
# WHERE FLAVOR IN


SELECT A.FLAVOR
FROM (

SELECT F.FLAVOR, (SUM(DISTINCT F.TOTAL_ORDER) + SUM(DISTINCT J.TOTAL_ORDER)) AS TOTAL
      FROM JULY J LEFT JOIN FIRST_HALF F ON F.FLAVOR = J.FLAVOR 
      GROUP BY F.FLAVOR
      
ORDER BY TOTAL DESC 
LIMIT 3
) A

# SELECT DISTINCT F.FLAVOR, F.TOTAL_ORDER
# FROM JULY J LEFT JOIN FIRST_HALF F ON F.FLAVOR = J.FLAVOR 









# SELECT J.FLAVOR
# FROM FIRST_HALF F JOIN JULY J ON F.SHIPMENT_ID = J.SHIPMENT_ID
# GROUP BY J.FLAVOR
# ORDER BY SUM(F.TOTAL_ORDER)+SUM(J.TOTAL_ORDER) DESC
# LIMIT 3