# SELECT A.APNT_NO, 
#         P.PT_NAME, 
#         P.PT_NO, 
#         A.MCDP_CD, (
#         SELECT DR_NAME 
#         FROM DOCTOR D 
#         WHERE D.DR_ID = A.MDDR_ID ) AS DR_NAME, 
#         A.APNT_YMD
# FROM PATIENT P JOIN APPOINTMENT A ON P.PT_NO = A.PT_NO
# WHERE A.MCDP_CD = 'CS' AND A.APNT_YMD LIKE '2022-04-13%'
# ORDER BY A.APNT_YMD


# 2022년 4월 13일 취소되지 않은 흉부외과(CS)

SELECT A.APNT_NO, 
        P.PT_NAME, 
        P.PT_NO, 
        A.MCDP_CD,
        D.DR_NAME,
        A.APNT_YMD
FROM PATIENT P JOIN APPOINTMENT A ON P.PT_NO = A.PT_NO JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
WHERE A.MCDP_CD = 'CS' AND A.APNT_YMD LIKE '2022-04-13%' AND A.APNT_CNCL_YN = 'N'
ORDER BY A.APNT_YMD