# 1. 둘 이상 등록된(중복되는) 공간
# SELECT HOST_ID
# FROM PLACES
# GROUP BY HOST_ID
# HAVING COUNT(*)>=2
# ORDER BY ID

# 2. 그 공간의 정보 
SELECT ID, NAME, HOST_ID
FROM PLACES 
WHERE HOST_ID IN (
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(*)>=2) 
ORDER BY ID