# SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, (
#     SELECT ROUND(AVG(B.REVIEW_SCORE),2)
#     FROM REST_REVIEW B 
#     WHERE A.REST_ID = B.REST_ID AND REVIEW_SCORE IS NOT NULL) AS SCORE
# FROM REST_INFO A
# WHERE ADDRESS LIKE '서울%'
# ORDER BY SCORE DESC, FAVORITES DESC;

SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(AVG(B.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO A JOIN REST_REVIEW B ON A.REST_ID = B.REST_ID
WHERE A.ADDRESS LIKE '서울%'
GROUP BY A.REST_NAME
ORDER BY SCORE DESC, A.FAVORITES DESC;